Plots by time
Aarhus-Psychiatry-Research/psycop-t2d pull request #140
Opened 2022-07-13 10:38 UTC by HLasse

Fixes #61

2022-07-14 08:02 UTC, MartinBernstorff requested changes
This looks excellent, Lasse! Really looking forward to seeing these plots!

One thing missing:
- [ ] Add the plots to `evaluate_model.py`

I've added a few comments as well. Some of them are a tad nitpicky, so feel free to disregard those. 

Looking forward to merge!

2022-07-15 08:11 UTC, HLasse commented on src/psycopt2d/visualization/performance_over_time.py
> +    y_title: str = "AUC",
Hm, unsure what the best way to go is. We would likely mainly use this for AUC on a monthly basis so having defaults would make calling the function a bit easier. But no strong opinion, will remove defaults for now

2022-07-15 08:16 UTC, HLasse commented on src/psycopt2d/visualization/performance_over_time.py
> +        drop_na_events (bool, optional): Whether to drop rows where the event is NA. Defaults to False.
Neccessary for plotting time until diagnosis (unless handled in the df beforehand). (agree on settng it to True by default)

2022-07-15 08:21 UTC, HLasse commented on src/psycopt2d/visualization/performance_over_time.py
> +        0,
I guess we need to handle this in `evaluate_models.py` to remove data points after the event has happened? Still, relevant to assess I think

2022-07-15 08:25 UTC, HLasse commented on src/psycopt2d/visualization/base_charts.py
> +            )
How do I accept your suggestion from vs code? (this is much better ;))

2022-07-15 09:57 UTC, MartinBernstorff commented on src/psycopt2d/visualization/base_charts.py
> +            )
Haha, you can't – but you can copy/paste it 👍

2022-07-15 09:58 UTC, MartinBernstorff commented on src/psycopt2d/visualization/performance_over_time.py
> +        drop_na_events (bool, optional): Whether to drop rows where the event is NA. Defaults to False.
Not quite sure I understand, but if default is True I'm good with it 👍

2022-07-15 10:00 UTC, MartinBernstorff commented on src/psycopt2d/visualization/performance_over_time.py
> +        0,
Hmm, I think this makes the plot harder to read, and they should be empty. I can see the argument for having the negative bins to catch errors, though. 

- [ ] Make the smallest interval 0-28 (i.e. remove -1, -7, -14, same with positives), otherwise many empty bins
- [ ] Let's leave it for now, and then people can generate two plots, one with and one without negative bins 👍

2022-07-15 10:01 UTC, MartinBernstorff commented
Looks great! When conversations have been resolved and it's been battle-tested on Overtaci, I think we're ready for merge 👍

2022-07-15 12:20 UTC, HLasse commented on src/psycopt2d/visualization/base_charts.py
> +            )
Exactly what I did ;) you just don't get the credit then!

2022-07-16 08:56 UTC, merged