Add feature importance. Fixes #111
Aarhus-Psychiatry-Research/psycop-t2d pull request #148
Opened 2022-07-16 10:01 UTC by HLasse

2022-07-25 08:32 UTC, KennethEnevoldsen commented on src/psycopt2d/config/evaluation/default_evaluation.yaml
> +top_n_feature_importances: 10
```suggestion
top_n_feature_importances: 10 # top n features to create the plot based on. We also log a table containing all features.
```

2022-07-25 08:33 UTC, KennethEnevoldsen commented on src/psycopt2d/evaluate_model.py
> +        # Handle EBM and other models a bit differently
```suggestion
        # Handle EBM differently as it autogenerated interaction terms
```

2022-07-25 08:36 UTC, KennethEnevoldsen commented on src/psycopt2d/visualization/feature_importance.py
> +        y_title="Feature importance",
Also add the actual metric name

2022-07-27 12:29 UTC, HLasse commented
@KennethEnevoldsen fixed changes. Accept so we can merge?

2022-08-17 09:20 UTC, HLasse commented
@KennethEnevoldsen !

2022-08-17 11:06 UTC, KennethEnevoldsen requested changes

2022-08-17 11:06 UTC, KennethEnevoldsen commented on src/psycopt2d/visualization/base_charts.py
> +        alt.Chart: _description_
Fix docstring

2022-08-17 11:06 UTC, KennethEnevoldsen commented on src/psycopt2d/evaluate_model.py
> +    train_col_names: Iterable[str],
missing docstring

2022-08-17 11:06 UTC, KennethEnevoldsen commented on src/psycopt2d/visualization/feature_importance.py
> +        feature_importances (np.ndarray): Feature importances
Error in arg name and missing argument description.

2022-08-17 11:10 UTC, KennethEnevoldsen commented
@HLasse, you can also use the re-request the review instead of @'ing

2022-08-17 11:12 UTC, HLasse commented
@KennethEnevoldsen I prefer the passive-aggressive @ <3

2022-08-22 14:26 UTC, KennethEnevoldsen requested changes
There were two errors in documentation. They should be a quick fix.

2022-08-22 14:26 UTC, KennethEnevoldsen commented on src/psycopt2d/evaluate_model.py
> +        run [wandb.run]: WandB run
```suggestion
        run (wandb.run): WandB run
```

2022-08-22 14:26 UTC, KennethEnevoldsen commented on src/psycopt2d/evaluate_model.py
> +        cfg (_type_): The hydra config from the run
missing type

2022-08-23 11:40 UTC, MartinBernstorff commented
Thanks for the review, @KennethEnevoldsen! If the changes are minor and uncontronversial (like these), I think it'd be good for us to just implement them as a reviewer. This'd remove one review cycle with little added cost. 

Let's try it and see how it goes :-)

2022-08-23 11:43 UTC, MartinBernstorff approved these changes

2022-08-23 11:45 UTC, MartinBernstorff commented
(When we "Request changes", there's no way for others to override. I'd love to merge the branch right now, but as far as I can see, there's no way for me to override your request 😉)

2022-08-23 12:04 UTC, KennethEnevoldsen approved these changes

2022-08-23 12:04 UTC, merged