Save model predictions
Aarhus-Psychiatry-Research/psycop-t2d pull request #190
Opened 2022-09-21 12:44 UTC by HLasse

- [X] I have battle-tested on Overtaci (RMAPPS1279)
- [ ] I have bumped the version as described in the [wiki](https://www.notion.so/Setting-up-Poetry-on-your-local-machine-76647d75e8fa4d9ba553cbc2a49946d9#dca1e0f2ce934a49acd1851aaf882d75)

## Notes for reviewers
Reviewers can skip X, but should pay attention to Y.
Fixes #182

2022-09-22 09:47 UTC, MartinBernstorff requested changes
Looks great, Lasse! A handful of comments – to make this useful, I think we especially want to document the intended flow for developing new evaluation plots.

This will be super useful! More speed! ❤️

2022-09-22 09:47 UTC, MartinBernstorff commented on src/psycopt2d/config/evaluation/default_evaluation.yaml
> +save_results_in_folder: false
Not a great key – `save_result_in_tmp_folder` instead? 😊

2022-09-22 09:47 UTC, MartinBernstorff commented on src/psycopt2d/config/evaluation/default_evaluation_synth.yaml
> +threshold_percentiles: [95, 97, 98, 99, 99.5, 99.7, 99.9]
Rename file to `evaluation_synth`?

2022-09-22 09:47 UTC, MartinBernstorff commented on src/psycopt2d/config/integration_testing.yaml
> +  - evaluation: default_evaluation_synth
```suggestion
  - evaluation: evaluation_synth
```

2022-09-22 09:47 UTC, MartinBernstorff commented on src/psycopt2d/evaluate_saved_model_predictions.py
> +    )
This is excellent! Exactly what we need. 

I guess we want some documentation as well, something like:

"If you're developing a new model evaluation plot, it's much faster to develop it if you don't have to train a model. 

We recommend that you:
1) Design the plot on synth prediction data
2) Test the plot on real prediction data on overtaci
"

And then point to the relevant points in the example.

2022-09-22 09:47 UTC, MartinBernstorff commented on src/psycopt2d/train_model.py
> +        OUTCOME_COL_NAME = "outc_dichotomous_t2d_within_30_days_max_fallback_0"
Rather than have an if statement, can we specify it in `cfg.data`?

2022-09-22 09:47 UTC, MartinBernstorff commented on src/psycopt2d/train_model.py
> +    df_with_metadata_to_disk(df=eval_dataset, cfg=cfg)
```suggestion
    # Save results to disk
    prediction_df_with_metadata_to_disk(df=eval_dataset, cfg=cfg)
```

2022-09-22 09:47 UTC, MartinBernstorff commented on src/psycopt2d/utils.py
> +            Path()
Where does this initialise the path? I.e. what is the "root"?

2022-09-22 09:47 UTC, MartinBernstorff commented on src/psycopt2d/utils.py
> +    """
```suggestion
    """Saves a dict with 
        key: prediction dataframe and 
        value: its corresponding hydra config 
     to disk.

    Args:
        df (pd.DataFrame): Dataframe to save.
        cfg (DictConfig): Hydra config.
    """
```

2022-09-22 09:47 UTC, MartinBernstorff commented on src/psycopt2d/visualization/altair_utils.py
> +    )
This function is unused? If we want to keep it, we should specify that it logs to a temp directory.

2022-09-22 12:47 UTC, HLasse commented on src/psycopt2d/utils.py
> +            Path()
`Path()` always uses the base of the project as the ´root´, so the top level directory where README.md etc are located

2022-09-22 12:53 UTC, HLasse commented on src/psycopt2d/visualization/altair_utils.py
> +    )
Unused for now, but I assume it will be useful making charts for publication or local exploration. 
Doesn't link to a temp directory, you pass the path to save in as an argument

2022-09-22 12:58 UTC, HLasse commented on src/psycopt2d/config/evaluation/default_evaluation.yaml
> +save_results_in_folder: false
Good point - rewrote the corresponding function (`prediction_df_with_metadata_to_disk`) and renamed for ease of use

2022-09-22 13:08 UTC, HLasse commented on src/psycopt2d/evaluate_saved_model_predictions.py
> +    )
Good call - added some pointers in the readme

2022-09-23 09:05 UTC, MartinBernstorff approved these changes

2022-09-23 09:37 UTC, HLasse commented on src/psycopt2d/config/data/synth_data.yaml
> +source: synthetic
Yep, in `load_dataset_from_config` - but will probably be deprecated once the scripts are updated to run from local files instead of sql

2022-09-28 10:38 UTC, HLasse commented
Note self: change the `Path()` calls to use the PROJECT_DIR_PATH

2022-09-28 10:43 UTC, merged

2022-09-28 11:04 UTC, MartinBernstorff commented
Hey @HLasse! Seems this was merged too early. Should we create a new issue for your comment?