add: log performance metrics
Aarhus-Psychiatry-Research/psycop-t2d pull request #73
Opened 2022-06-22 13:02 UTC by HLasse

2022-06-22 13:04 UTC, HLasse commented
Closes #29

2022-06-22 13:34 UTC, martbern requested changes

2022-06-22 13:34 UTC, martbern commented on src/psycopt2d/utils.py
>      # Only 1 row, so taking it out
What does each row represent here? 

Do we also get performance metrics by visit?

2022-06-22 13:34 UTC, martbern commented on tests/test_calculate_performance_metrics.py
> +    wandb.finish()
Will never pass on github actions because we don't have a wandb setup. Perhaps just remove wandb lines? :-)

2022-06-23 07:45 UTC, martbern commented on src/psycopt2d/utils.py
>      # Only 1 row, so taking it out
```suggestion
```

2022-06-23 07:52 UTC, martbern approved these changes

2022-06-23 07:52 UTC, merged